emailGenerator/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('generator/', include('generator.urls'))
]

generator/urls.py
from django.urls import path
from . import views
# importowanie z views, kropkę wstawiamy jeżli pobiebramy z tego samego folderu

app_name = 'generator'

urlpatterns = [
    path('', views.home, name='home'),
    path('result', views.result, name='result'),
    path('about', views.about, name='about')
]

generator/models.py
from django.db import models

# Create your models here.

generator/views.py
from django.shortcuts import redirect, render
import random

# Create your views here.
def home(request):
    return render(request, 'home.html')

def result(request):
    if request.method == 'POST':
        characters = 'abcdefghijklmnoprstuwvxyz'
        numbers = '1234567890'
        special = '!@#$%&'

        if request.POST.get('numbers'):
            characters += numbers
  
        if request.POST.get('special'):
            characters += special      
        
        length = int(request.POST.get('length'))
        domain = request.POST.get('domain')

        preMail = ''

        for _ in range(length):
            preMail += random.choice(characters)

        mail = preMail + domain


        return render(request, 'result.html', {'mail': mail})
    else:
        return redirect('generator:home')

def about(request):
    return render(request, 'about.html')

generator/templates/about.html
{% extends 'base.html' %}
{% block content %} 
<div class="container text text-center">
    <br>
    <p class= 'alert alert-info'> Created by Agata </p>

    <a class="btn btn-info" href= "{% url 'generator:home' %}" > Home </a>

</div>
{% endblock content%}

generator/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %} {% endblock content%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

generator/templates/home.html
{% extends 'base.html' %}
{% block content %} 

<div class="container text text-center">
    <h1>E-mail Generator</h1>
    <form action="{% url 'generator:result' %}" method="POST">
        <select name = 'length' required>
            <option value="" disabled selected>Choose length</option>
            <option value="6">6 characters</option>
            <option value="7">7 characters</option>
            <option value="8">8 characters</option>
            <option value="9">9 characters</option>
            <option value="10">10 characters</option>
        </select>
        <br>
        <br>
        <select name="domain" required>
            <option value="" disabled selected>Choose domain</option>
            <option value="@gmail.com">Gmail</option>
            <option value="@interia.pl">Interia</option>
            <option value="@o2.pl">O2</option>       
        </select>
        <br>
        <br>
        <label for="numbers">Include numbers</label>
        <input type="checkbox" id="numbers" name="numbers">
        <br>
        <br>
        <label for="special">Include special characters</label>
        <input type="checkbox" id="special" name="special">
        <br>
        <br>
        {% csrf_token %}
        <button class="btn btn-success" type="submit">Generate</button>

    </form>
    <br>
    <a class="btn btn-outline-info" href= "{% url 'generator:about' %}" > About page </a>     
</div>
{% endblock content%}

generator/templates/result.html
{% extends 'base.html' %}
{% block content %} 

<div class="container text text-center">
    <h1>Result</h1>

    <div class="alert alert-primary" >
    {{mail}}
    </div>


    <a class="btn btn-info" href= "{% url 'generator:home' %}" > Home </a> 

</div>
{% endblock content%}